Overhaul pre-commit hook
 * More robust file status filtering using 'git ls-files'
 * which avoids the non-portable use of 'findstr'.
 * Use a pipe plus while-loop over command subsitution plus for-loop.
 * Get rid of useless recursive invocation of 'grep'.
 * Use printf how it's supposed to be used to make it more robust:
   with argument format specifiers.
 * Make the script file executable.

Among other benefits, this should enable *nix users to submit pull
requests for translation and data changes.

diff --git a/git/hooks/pre-commit b/git/hooks/pre-commit
--- a/git/hooks/pre-commit
+++ b/git/hooks/pre-commit
@@ -8,25 +8,17 @@
 # To enable this hook, rename this file to "pre-commit".
 #set -x
 
-List=$(git status | findstr modified | findstr app.config | cut -d ":" -f2 | xargs)
 exitstatus=0
-
-for f in "$List"
+git ls-files --modified --exclude-standard ':/**/app.config' |
+while read -r f
 do
-	if [ ${#f} -ge 1 ] 
-	then 
-		if grep -Rq "<nlog>" $f
-		then
-			printf "Please remove the nlog-block in file $f!"
-			exitstatus=1
-		else
-			printf "NLog not found in $f."
-		fi
+	if grep -q "<nlog>" "$f"
+	then
+		printf 'Please remove the nlog-block in file %s!\n' "$f"
+		exitstatus=1
 	else
-		printf "Variable is empty"
+		printf 'NLog not found in %s.\n' "$f"
 	fi
 done
 
-exit $exitstatus
-
-
+exit "$exitstatus"
